title: Ida Tarbell
description: "A free (but incomplete) archive of Ida Tarbell's writing"
baseurl: ""
url: "http://muckrackers.github.io/ida-tarbell/" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title/
markdown: kramdown

prose:
  media: "img"
