# Site settings
title: Ida Tarbell
email: ben.welsh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A free (but incomplete) archive of Ida Tarbell's writing
baseurl: ""
url: "http://muckrackers.github.io/ida-tarbell/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
