title: Ida Tarbell
description: "A free (but incomplete) archive of Ida Tarbell's writing"
baseurl: "/ida-tarbell"
url: "http://muckrackers.github.io"
permalink: /:year/:month/:day/:title/
markdown: kramdown

prose:
  media: "img"
